### ISSUE TITLE
Add tests to verify function of reverse PTR entries

### ISSUE THREAD

**Issue by href** [cloudscale-ch/acceptance-tests#8]
When creating/updating a server, or creating/updating a Floating IP, it is possible to set a reverse PTR record.

See `reverse_ptr` on https://www.cloudscale.ch/en/api/v1.

We need to add two tests that verify that the reverse PTR can be set and that querying it using standard DNS tools works:

* One test for servers
* One test for Floating IPs

There should be a maximum amount of time that this takes and we need to ensure that creating bogus records does not work and returns a useful error message.

**Comment by subsecond** [comment]
Implemented in https://github.com/cloudscale-ch/acceptance-tests/pull/11
